### ISSUE TITLE
Update to Angular 5/6

### ISSUE THREAD

**Issue by MatteoJoliveau** [TechGapItalia/angular-vertical-timeline#10]
Should update the timeline to use at least Angular 5, if not even 6.

**Comment by cbrignani** [comment]
Done with version 0.6.0

**Comment by anuj509** [comment]
@MatteoJoliveau were you able to install in angular 6 ?

**Comment by MatteoJoliveau** [comment]
@anuj509 I'm not actively maintaining this project anymore, so you have to ask this to TechGap staff.

/cc @cbrignani @nanomad

**Comment by nanomad** [comment]
@anuj509 Yes. Just remember to install rxjs compat libraries as well. It's currently used in production code along with Angular 6
