### ISSUE TITLE
Angular CLI can not AOT Compile this

### ISSUE THREAD

**Issue by ajayrcdev** [TechGapItalia/angular-vertical-timeline#7]
Getting following when doing ng build --prod:

`ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 7:9 in theoriginal .ts file), resolving symbol ɵa in /Users/ajayrc/DEV/ngtimelineaottest/node_modules/angular-vertical-timeline/angular-vertical-timeline.d.ts
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/ajayrc/DEV/ngtimelineaottest/src'
resolve './$$_gendir/app/app.module.ngfactory' in '/Users/ajayrc/DEV/ngtimelineaottest/src'
  using description file: /Users/ajayrc/DEV/ngtimelineaottest/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/ajayrc/DEV/ngtimelineaottest/package.json (relative path: ./src)
    using description file: /Users/ajayrc/DEV/ngtimelineaottest/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      as directory
        /Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory doesn't exist
[/Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory]
[/Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory.ts]
[/Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory.js]
[/Users/ajayrc/DEV/ngtimelineaottest/src/$$_gendir/app/app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts`

Current config:

`"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-vertical-timeline": "^0.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }`

**Comment by savageqm** [comment]
any updates on this?

**Comment by netstart** [comment]
https://github.com/jvandemo/generator-angular2-library/issues/149
https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5

**Comment by MatteoJoliveau** [comment]
We're working on it and will probably be merged in master today. We just merged PR #8

**Comment by MatteoJoliveau** [comment]
I confirm that version 0.3.0 is compatible with AOT. You can find it on NPM starting by now.
![image](https://user-images.githubusercontent.com/9077612/34726943-bf62545a-f555-11e7-82b5-d906b4199600.png)
